version: '3'

services:
    master:
        build: ./cluster
        ports:
            - "9000:9000"
            - "2200:22"
            - "50070:50070"
        networks:
            - cluster
        volumes:
            - "./flags:/usr/src/flags"
            - "./applications:/usr/src/applications"
            - "hdfsdata:/usr/src/hdfsdata"
        command: "./master.sh"
        depends_on: 
            - slave1
            - slave2
    slave1:
        build: ./cluster
        ports:
            - "2201:22"
        networks:
            - cluster
        volumes:
            - "hdfsdata:/usr/src/hdfsdata"
        command: ./slave.sh
    slave2:
        build: ./cluster
        ports:
            - "2202:22"
        networks:
            - cluster
        volumes:
            - "hdfsdata:/usr/src/hdfsdata"
        command: ./slave.sh
    zeppelin:
        build: ./zeppelin
        ports:
            - "8080:8080"
        volumes:
            - "./notebooks:/usr/src/notebooks"
            - "./data:/usr/src/data"

networks:
    cluster:
        driver: bridge

volumes: 
    hdfsdata:
